server:
  port: 8088

spring:
  application:
    name: utilisateur
  datasource:
    url: jdbc:postgresql://localhost:5227/utilisateur_microservice
    username: utilisateur_microservice
    password: utilisateur_microservice
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/chic-choice
debug: false

