server:
  port: 9999

spring:
  application:
    name: media
  datasource:
    url: jdbc:postgresql://localhost:5229/media_microservice
    username: media_microservice
    password: media_microservice
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

error:
  handling:
    http-statuses:
      jakarta:
        persistence:
          EntityNotFoundException: not_found
          EntityExistsException: conflict

    http-status-in-json-response: true
debug: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
