spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vetement
          uri: lb://VETEMENT
          predicates:
            - Path=/api/v1/vetements/**
        - id: ensemble
          uri: lb://VETEMENT
          predicates:
            - Path=/api/v1/ensembles/**
        - id: couleur
          uri: lb://COULEUR
          predicates:
            - Path=/api/v1/couleurs/**
        - id: media
          uri: lb://MEDIA
          predicates:
            - Path=/api/v1/media/**
        - id: utilisateur
          uri: lb://UTILISATEUR
          predicates:
            - Path=/api/v1/users/**
        - id: planification
          uri: lb://PLANIFICATION
          predicates:
            - Path=/api/v1/planfications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/chic-choice/protocol/openid-connect/certs
server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
