server:
  port: 8087

spring:
  application:
    name: couleur
  datasource:
    url: jdbc:postgresql://localhost:5228/couleur_microservice
    username: couleur_microservice
    password: couleur_microservice
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


debug: false
