server:
  port: 8090

spring:
  application:
    name: meteo
  datasource:
    url: jdbc:postgresql://localhost:5223/meteo_microservice
    username: meteo_microservice
    password: meteo_microservice
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


debug: false

